### ISSUE TITLE
Fightus Contact Form

### ISSUE THREAD

**Issue by Chelrid** [erfurtjohn/eu.cywa.wcf.clanwars#10]
Kann man das Plugin vielleicht auch noch um eine Kontaktanfrage-Funktion erweitern, so dass andere Clans als unregistrierter User einen CW Anfrage versenden können?

**Comment by erfurtjohn** [comment]
Das ist in Arbeit, kann aber nicht garantieren, wann das kommt. Zuerst sollte das eigene Hinzufügen von Spielen funktionieren.
